CREATE DATABASE trabalho;

USE trabalho;

CREATE TABLE clientes (
    id INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(150) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefone VARCHAR(15) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Senha VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);